name: Continuous Integration

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run type-check

      # - name: Run linting
      #   run: npm run lint

      # - name: Run tests
      #   run: npm test

  docker-build-test:
    runs-on: ubuntu-latest
    needs: lint-and-test

    strategy:
      matrix:
        target: [development, production]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: ${{ matrix.target }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: web3fygo:${{ matrix.target }}-${{ github.sha }}

      - name: Test Docker image
        run: |
          docker run --rm -d --name test-container \
            -p 3000:3000 \
            web3fygo:${{ matrix.target }}-${{ github.sha }}
          
          # Wait for container to start
          sleep 10
          
          # Test health endpoint
          curl -f http://localhost:3000/api/health || exit 1
          
          # Clean up
          docker stop test-container

  security-scan:
    runs-on: ubuntu-latest
    needs: docker-build-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' 